version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: foodgram_db
    restart: always
    environment:
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: strong_password_123
      POSTGRES_DB: foodgram
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram_user -d foodgram"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: foodgram_backend
    restart: always
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: foodgram
      DB_USER: foodgram_user
      DB_PASSWORD: strong_password_123
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: django-insecure-very-secret-key-change-it
      DEBUG: 'False'
      ALLOWED_HOSTS: 158.160.229.49,localhost,127.0.0.1,phudgrum.abrdns.com
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 foodgram.wsgi:application"

  nginx:
    image: nginx:alpine
    container_name: foodgram_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:

