server {
    listen 80;
    server_name phudgrum.abrdns.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name phudgrum.abrdns.com;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    client_max_body_size 10M;

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location /media/ {
        alias /media/;
    }

    location /api/ {
        proxy_pass http://foodgram_backend:8000;
        proxy_set_header Host phudgrum.abrdns.com;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://foodgram_backend:8000;
        proxy_set_header Host phudgrum.abrdns.com;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/s/(\d+)/?$ {
        return 301 https://phudgrum.abrdns.com/recipes/$1;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}

