server {
    listen 80;
    server_name 158.160.229.49 phudgrum.abrdns.com;

    client_max_body_size 10M;

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location /media/ {
        alias /media/;
    }

    location /api/ {
        proxy_pass http://foodgram_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://foodgram_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}
